services:
  tileset-gen:
    build:
      dockerfile: Dockerfile
      tags:
        - "tileset-gen:latest"
    volumes:
      - $PWD/out:/app/out
    environment:
      - GRAPHQL_TOKEN=${GRAPHQL_TOKEN}
